name: "Erik Bj&auml;reholt - Personal website"
email: erik@bjareho.lt
description: >
  Blog, personal wiki, and stuff about me.
baseurl: ""
url: "https://erik.bjareholt.com"

# Build settings
markdown: kramdown
highlighter: rouge
timezone: Europe/Stockholm

collections:
    wiki:
        output: true
        permalink: /wiki/:title/
    blog:
        output: true
        permalink: /blog/:year/:month/:day/:title/

defaults:
    - scope:
        path: ""
        type: "wiki"
      values:
        layout: wikipage
    - scope:
        path: ""
        type: "blog"
      values:
        layout: blogpost

sass:
    sass_dir: _sass

plugins:
 - jekyll-redirect-from
 - jekyll-last-modified-at
 - jekyll-pug
 - jekyll-feed
