name: "Erik Bj&auml;reholt"
description: "Towards a better tomorrow, today!"
url: "http://erik.bjareholt.com"
markdown: kramdown
highlighter: rouge
timezone: Europe/Stockholm

collections:
    wiki:
        output: true
        permalink: /wiki/:title/
    blog:
        output: true
        permalink: /blog/:year/:month/:day/:title/

defaults:
    - scope:
        path: ""
        type: "wiki"
      values:
        layout: wikipage
    - scope:
        path: ""
        type: "blog"
      values:
        layout: blogpost

gems:
 - jekyll-compass
 - jekyll-redirect-from
 - jekyll-last-modified-at
